server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  webflux:
    static-path-pattern: /**
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: changeMeChangeMeChangeMeChangeMe123
          ttl-days: 30
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: oauth2-service
          uri: lb://oauth2-service
          predicates:
            - Path=/api-app/duck-smoking/v1.0.0/oauth2-service/**
          filters:
            - StripPrefix=3

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    oauth:
      use-basic-authentication-with-access-code-grant: false
    persist-authorization: true
    path: /swagger-ui.html
    enabled: true
    urls:

      - name: oauth2-service
        url: /api-app/duck-smoking/v1.0.0/oauth2-service/v3/api-docs

    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh, info, health, metrics, loggers, httptrace
  endpoint:
    health:
      show-details: always
