server:
  port: 8084
spring:
  application:
    name: user-service
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: ALWAYS
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: changeMeChangeMeChangeMeChangeMe123
#          jwk-set-uri: http://auth-service:8081/.well-known/jwks.json
      client:
        registration:
          google:
            client-id: 99125590092-f7c91gdsgs5mihdp7jaghch4nhfkv4fm.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            issuer-uri: https://accounts.google.com
  mail:
    host: smtp.gmail.com
    port: 587
    username: brosakh097@gmail.com
    password: enbckqagjriwwrpj
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

